# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7e175fb44404a17ea4068efb430d45ef95d0797fb070f75fb6576e5e5618f5792950406206ded1d6a9c175950d961669e6d2c0b1df280b4c16bc8790e7b55a

test:
  secret_key_base: e02e5ae2d6d2b270e9db61622bd2d6f0047e588b52806d7dbec7b1c4d100566b9d153d9bf418d7cf316a9474b5de0e0fc1a2c72862c1e34faa51471631599db2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
